conf = {

	HEIGHT = application:getContentHeight(),
	WIDTH = application:getContentWidth(),
	TRANSITION_TIME = 1,
	BG_SCALE = 1,
	START_BUTTON_SCALE = 0.5,
	LEVEL_BG_SCALE = 5,
	HERO_SCALE = 4,
	ENEMY_SCALE = 3.2,
	ENEMY_SPEED = 2.5,
	MAX_ENEMY_COUNT = 15,
	SCORE_SCALE = 2,
	TUMBLEWEED_SCALE = 2,
	CLOUDS_SCALE_X = 1920 / 140,
	CLOUDS_SCALE_Y = 1080 / 45,
	CLOUDS_SPEED = 1.2,
	STARS_SCALE_X = 1920 / 140,
	STARS_SCALE_Y = 1080 / 45,
	STARS_ALPHA = 0.4,
	
}