conf = {

	HEIGHT = application:getContentHeight(),
	WIDTH = application:getContentWidth(),
	SCREENW = application:getDeviceHeight(),
	SCREENH = application:getDeviceWidth(),
	TRANSITION_TIME = 1,
	MENU_BG_SCALE_X = 1920 / 400,
	MENU_BG_SCALE_Y = 1080 / 225,
	GAMEOVER_BG_SCALE_X = 1920 / 400,
	GAMEOVER_BG_SCALE_Y = 1080 / 225,
	START_BUTTON_SCALE = 4.5,
	LEVEL_BG_SCALE = 5,
    CAM_SPEED = 0.2,
	HERO_SCALE = 4,
	ENEMY_SCALE = 3.2,
	ENEMY_SPEED = 2.5,
	MAX_ENEMY_COUNT = 15,
	SCORE_SCALE = 2,
	TUMBLEWEED_SCALE = 2,
	CLOUDS_SCALE_X = 1920 / 140,
	CLOUDS_SCALE_Y = 1080 / 45,
	CLOUDS_SPEED = 1.2,
	CLOUDS_ALPHA = 0.6,
	STARS_SCALE_X = 1920 / 140,
	STARS_SCALE_Y = 1080 / 45,
	STARS_ALPHA = 0.4,
	LOGO_SCALE = 4,
	RETRY_BUTTON_SCALE = 4,
	
}